# Static-link the MSVC C runtime on Windows so the release binary and the
# packaged zip (packaging/windows/build-zip.ps1) run without the Visual C++
# Redistributable installed. Scoped to the MSVC target, so the macOS and Linux
# builds are unaffected.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
